namespace: "softasap"
name: "oops_box"
description: wraps sa_traefik and sa_docker to prepare hosts from traefik_box group for further provisioning
version: "0.0.1"
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
repository: "https://github.com/oops-to-devops/oops_box_template"
documentation: "https://github.com/oops-to-devops/oops_box_template/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
